/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as CirclesIndexRouteImport } from './routes/circles.index'
import { Route as ActivityIndexRouteImport } from './routes/activity.index'
import { Route as CirclesJoinRouteImport } from './routes/circles.join'
import { Route as CirclesCreateRouteImport } from './routes/circles.create'
import { Route as CirclesIdRouteImport } from './routes/circles.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesIndexRoute = CirclesIndexRouteImport.update({
  id: '/circles/',
  path: '/circles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesJoinRoute = CirclesJoinRouteImport.update({
  id: '/circles/join',
  path: '/circles/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesCreateRoute = CirclesCreateRouteImport.update({
  id: '/circles/create',
  path: '/circles/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesIdRoute = CirclesIdRouteImport.update({
  id: '/circles/$id',
  path: '/circles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/circles/$id': typeof CirclesIdRoute
  '/circles/create': typeof CirclesCreateRoute
  '/circles/join': typeof CirclesJoinRoute
  '/activity/': typeof ActivityIndexRoute
  '/circles/': typeof CirclesIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/circles/$id': typeof CirclesIdRoute
  '/circles/create': typeof CirclesCreateRoute
  '/circles/join': typeof CirclesJoinRoute
  '/activity': typeof ActivityIndexRoute
  '/circles': typeof CirclesIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/circles/$id': typeof CirclesIdRoute
  '/circles/create': typeof CirclesCreateRoute
  '/circles/join': typeof CirclesJoinRoute
  '/activity/': typeof ActivityIndexRoute
  '/circles/': typeof CirclesIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/circles/$id'
    | '/circles/create'
    | '/circles/join'
    | '/activity/'
    | '/circles/'
    | '/payments/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/circles/$id'
    | '/circles/create'
    | '/circles/join'
    | '/activity'
    | '/circles'
    | '/payments'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/circles/$id'
    | '/circles/create'
    | '/circles/join'
    | '/activity/'
    | '/circles/'
    | '/payments/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  CirclesIdRoute: typeof CirclesIdRoute
  CirclesCreateRoute: typeof CirclesCreateRoute
  CirclesJoinRoute: typeof CirclesJoinRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
  CirclesIndexRoute: typeof CirclesIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/': {
      id: '/circles/'
      path: '/circles'
      fullPath: '/circles/'
      preLoaderRoute: typeof CirclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/join': {
      id: '/circles/join'
      path: '/circles/join'
      fullPath: '/circles/join'
      preLoaderRoute: typeof CirclesJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/create': {
      id: '/circles/create'
      path: '/circles/create'
      fullPath: '/circles/create'
      preLoaderRoute: typeof CirclesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/$id': {
      id: '/circles/$id'
      path: '/circles/$id'
      fullPath: '/circles/$id'
      preLoaderRoute: typeof CirclesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  CirclesIdRoute: CirclesIdRoute,
  CirclesCreateRoute: CirclesCreateRoute,
  CirclesJoinRoute: CirclesJoinRoute,
  ActivityIndexRoute: ActivityIndexRoute,
  CirclesIndexRoute: CirclesIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
